version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=teams
      - POSTGRES_PASSWORD=teams
      - POSTGRES_DB=teams
      - SCHEMA=public
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/teams

volumes:
  postgres-db:
    driver: local