// Code generated by ent, DO NOT EDIT.

package ent

import (
	"project-service/repository/ent/attachment"
	"project-service/repository/ent/project"
	"project-service/repository/ent/schema"
	"project-service/repository/ent/team"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescCreatedAt is the schema descriptor for created_at field.
	attachmentDescCreatedAt := attachmentFields[5].Descriptor()
	// attachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachment.DefaultCreatedAt = attachmentDescCreatedAt.Default.(time.Time)
	// attachmentDescUpdatedAt is the schema descriptor for updated_at field.
	attachmentDescUpdatedAt := attachmentFields[6].Descriptor()
	// attachment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attachment.DefaultUpdatedAt = attachmentDescUpdatedAt.Default.(time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[6].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[7].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(time.Time)
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescAssignedAt is the schema descriptor for assigned_at field.
	teamDescAssignedAt := teamFields[4].Descriptor()
	// team.DefaultAssignedAt holds the default value on creation for the assigned_at field.
	team.DefaultAssignedAt = teamDescAssignedAt.Default.(time.Time)
	// teamDescUpdatedAt is the schema descriptor for updated_at field.
	teamDescUpdatedAt := teamFields[5].Descriptor()
	// team.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	team.DefaultUpdatedAt = teamDescUpdatedAt.Default.(time.Time)
}
