// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-service/repository/ent/member"
	"project-service/repository/ent/predicate"
	"project-service/repository/ent/project"
	"project-service/repository/ent/team"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (tu *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetProjectID sets the "project_id" field.
func (tu *TeamUpdate) SetProjectID(s string) *TeamUpdate {
	tu.mutation.SetProjectID(s)
	return tu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tu *TeamUpdate) SetNillableProjectID(s *string) *TeamUpdate {
	if s != nil {
		tu.SetProjectID(*s)
	}
	return tu
}

// ClearProjectID clears the value of the "project_id" field.
func (tu *TeamUpdate) ClearProjectID() *TeamUpdate {
	tu.mutation.ClearProjectID()
	return tu
}

// SetStatus sets the "status" field.
func (tu *TeamUpdate) SetStatus(t team.Status) *TeamUpdate {
	tu.mutation.SetStatus(t)
	return tu
}

// SetAssignedBy sets the "assigned_by" field.
func (tu *TeamUpdate) SetAssignedBy(s string) *TeamUpdate {
	tu.mutation.SetAssignedBy(s)
	return tu
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (tu *TeamUpdate) SetNillableAssignedBy(s *string) *TeamUpdate {
	if s != nil {
		tu.SetAssignedBy(*s)
	}
	return tu
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (tu *TeamUpdate) ClearAssignedBy() *TeamUpdate {
	tu.mutation.ClearAssignedBy()
	return tu
}

// SetAssignedAt sets the "assigned_at" field.
func (tu *TeamUpdate) SetAssignedAt(t time.Time) *TeamUpdate {
	tu.mutation.SetAssignedAt(t)
	return tu
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (tu *TeamUpdate) SetNillableAssignedAt(t *time.Time) *TeamUpdate {
	if t != nil {
		tu.SetAssignedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TeamUpdate) SetUpdatedAt(t time.Time) *TeamUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tu *TeamUpdate) SetNillableUpdatedAt(t *time.Time) *TeamUpdate {
	if t != nil {
		tu.SetUpdatedAt(*t)
	}
	return tu
}

// SetAssignByID sets the "assignBy" edge to the Member entity by ID.
func (tu *TeamUpdate) SetAssignByID(id string) *TeamUpdate {
	tu.mutation.SetAssignByID(id)
	return tu
}

// SetNillableAssignByID sets the "assignBy" edge to the Member entity by ID if the given value is not nil.
func (tu *TeamUpdate) SetNillableAssignByID(id *string) *TeamUpdate {
	if id != nil {
		tu = tu.SetAssignByID(*id)
	}
	return tu
}

// SetAssignBy sets the "assignBy" edge to the Member entity.
func (tu *TeamUpdate) SetAssignBy(m *Member) *TeamUpdate {
	return tu.SetAssignByID(m.ID)
}

// SetAssignationID sets the "assignation" edge to the Project entity by ID.
func (tu *TeamUpdate) SetAssignationID(id string) *TeamUpdate {
	tu.mutation.SetAssignationID(id)
	return tu
}

// SetNillableAssignationID sets the "assignation" edge to the Project entity by ID if the given value is not nil.
func (tu *TeamUpdate) SetNillableAssignationID(id *string) *TeamUpdate {
	if id != nil {
		tu = tu.SetAssignationID(*id)
	}
	return tu
}

// SetAssignation sets the "assignation" edge to the Project entity.
func (tu *TeamUpdate) SetAssignation(p *Project) *TeamUpdate {
	return tu.SetAssignationID(p.ID)
}

// Mutation returns the TeamMutation object of the builder.
func (tu *TeamUpdate) Mutation() *TeamMutation {
	return tu.mutation
}

// ClearAssignBy clears the "assignBy" edge to the Member entity.
func (tu *TeamUpdate) ClearAssignBy() *TeamUpdate {
	tu.mutation.ClearAssignBy()
	return tu
}

// ClearAssignation clears the "assignation" edge to the Project entity.
func (tu *TeamUpdate) ClearAssignation() *TeamUpdate {
	tu.mutation.ClearAssignation()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TeamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TeamUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TeamUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TeamUpdate) check() error {
	if v, ok := tu.mutation.Status(); ok {
		if err := team.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	return nil
}

func (tu *TeamUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeString))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.AssignedAt(); ok {
		_spec.SetField(team.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if tu.mutation.AssignByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignByTable,
			Columns: []string{team.AssignByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.AssignByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignByTable,
			Columns: []string{team.AssignByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.AssignationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignationTable,
			Columns: []string{team.AssignationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.AssignationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignationTable,
			Columns: []string{team.AssignationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetProjectID sets the "project_id" field.
func (tuo *TeamUpdateOne) SetProjectID(s string) *TeamUpdateOne {
	tuo.mutation.SetProjectID(s)
	return tuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tuo *TeamUpdateOne) SetNillableProjectID(s *string) *TeamUpdateOne {
	if s != nil {
		tuo.SetProjectID(*s)
	}
	return tuo
}

// ClearProjectID clears the value of the "project_id" field.
func (tuo *TeamUpdateOne) ClearProjectID() *TeamUpdateOne {
	tuo.mutation.ClearProjectID()
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *TeamUpdateOne) SetStatus(t team.Status) *TeamUpdateOne {
	tuo.mutation.SetStatus(t)
	return tuo
}

// SetAssignedBy sets the "assigned_by" field.
func (tuo *TeamUpdateOne) SetAssignedBy(s string) *TeamUpdateOne {
	tuo.mutation.SetAssignedBy(s)
	return tuo
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (tuo *TeamUpdateOne) SetNillableAssignedBy(s *string) *TeamUpdateOne {
	if s != nil {
		tuo.SetAssignedBy(*s)
	}
	return tuo
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (tuo *TeamUpdateOne) ClearAssignedBy() *TeamUpdateOne {
	tuo.mutation.ClearAssignedBy()
	return tuo
}

// SetAssignedAt sets the "assigned_at" field.
func (tuo *TeamUpdateOne) SetAssignedAt(t time.Time) *TeamUpdateOne {
	tuo.mutation.SetAssignedAt(t)
	return tuo
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (tuo *TeamUpdateOne) SetNillableAssignedAt(t *time.Time) *TeamUpdateOne {
	if t != nil {
		tuo.SetAssignedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TeamUpdateOne) SetUpdatedAt(t time.Time) *TeamUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tuo *TeamUpdateOne) SetNillableUpdatedAt(t *time.Time) *TeamUpdateOne {
	if t != nil {
		tuo.SetUpdatedAt(*t)
	}
	return tuo
}

// SetAssignByID sets the "assignBy" edge to the Member entity by ID.
func (tuo *TeamUpdateOne) SetAssignByID(id string) *TeamUpdateOne {
	tuo.mutation.SetAssignByID(id)
	return tuo
}

// SetNillableAssignByID sets the "assignBy" edge to the Member entity by ID if the given value is not nil.
func (tuo *TeamUpdateOne) SetNillableAssignByID(id *string) *TeamUpdateOne {
	if id != nil {
		tuo = tuo.SetAssignByID(*id)
	}
	return tuo
}

// SetAssignBy sets the "assignBy" edge to the Member entity.
func (tuo *TeamUpdateOne) SetAssignBy(m *Member) *TeamUpdateOne {
	return tuo.SetAssignByID(m.ID)
}

// SetAssignationID sets the "assignation" edge to the Project entity by ID.
func (tuo *TeamUpdateOne) SetAssignationID(id string) *TeamUpdateOne {
	tuo.mutation.SetAssignationID(id)
	return tuo
}

// SetNillableAssignationID sets the "assignation" edge to the Project entity by ID if the given value is not nil.
func (tuo *TeamUpdateOne) SetNillableAssignationID(id *string) *TeamUpdateOne {
	if id != nil {
		tuo = tuo.SetAssignationID(*id)
	}
	return tuo
}

// SetAssignation sets the "assignation" edge to the Project entity.
func (tuo *TeamUpdateOne) SetAssignation(p *Project) *TeamUpdateOne {
	return tuo.SetAssignationID(p.ID)
}

// Mutation returns the TeamMutation object of the builder.
func (tuo *TeamUpdateOne) Mutation() *TeamMutation {
	return tuo.mutation
}

// ClearAssignBy clears the "assignBy" edge to the Member entity.
func (tuo *TeamUpdateOne) ClearAssignBy() *TeamUpdateOne {
	tuo.mutation.ClearAssignBy()
	return tuo
}

// ClearAssignation clears the "assignation" edge to the Project entity.
func (tuo *TeamUpdateOne) ClearAssignation() *TeamUpdateOne {
	tuo.mutation.ClearAssignation()
	return tuo
}

// Where appends a list predicates to the TeamUpdate builder.
func (tuo *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Team entity.
func (tuo *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TeamUpdateOne) check() error {
	if v, ok := tuo.mutation.Status(); ok {
		if err := team.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	return nil
}

func (tuo *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeString))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.AssignedAt(); ok {
		_spec.SetField(team.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(team.FieldUpdatedAt, field.TypeTime, value)
	}
	if tuo.mutation.AssignByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignByTable,
			Columns: []string{team.AssignByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.AssignByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignByTable,
			Columns: []string{team.AssignByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.AssignationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignationTable,
			Columns: []string{team.AssignationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.AssignationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.AssignationTable,
			Columns: []string{team.AssignationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Team{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
