version: "3.8"
services:
  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - keycloak
      - team-service

  team-service:
    build:
      context: ./../team-service
      dockerfile: ./../team-service/deploy/image/team-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1

  user-service:
    build:
      context: ./../user-service
      dockerfile: ./../user-service/deploy/image/user-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on: [keycloak]
    env_file:
      - ./user-service.env
    networks: ["nats", "keycloak-network"]

  nats:
    image: nats
    ports:
      - "4222:4222"
    command: "-js"
    networks: ["nats"]

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: -v start-dev --import-realm
    env_file:
      - ./keycloak-postgres.env
    ports:
      - 8890:8080
    networks:
      - keycloak-network
    depends_on:
      keycloak-db:
        condition: service_healthy
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ./keycloak/themes/keywind.jar:/opt/keycloak/providers/keywind.jar

  keycloak-db:
    image: postgres:latest
    env_file:
      - ./keycloak-postgres.env
    healthcheck:
      test: "exit 0"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
  nats:
    name: nats
