// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)
